Fixed bug "AttributeError: 'dict' object has no attribute 'name' "  (#37)
* Fixed bug 'AttributeError: 'dict' object has no attribute 'name' ' Due to Issue #35 -> https://github.com/aashutoshrathi/git-stalk-cli/issues/35